// Generated by CoffeeScript 1.7.1
(function() {
  describe("The duck", function() {
    return it("contains spec with an expectation", function() {
      return expect(true).toBe(false);
    });
  });

}).call(this);
